//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTMENT()
        {
            this.EMPLOYEES_COFFEE = new HashSet<EMPLOYEES_COFFEE>();
        }
    
        public string DEP_ID { get; set; }
        public string DEP_NAME { get; set; }
        public Nullable<decimal> BASE_SALARY { get; set; }
        public Nullable<decimal> WAGE_PER_HOURS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEES_COFFEE> EMPLOYEES_COFFEE { get; set; }
    }
}
