//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_HISTORY
    {
        public string EMP_ID { get; set; }
        public string EMP_START_TIME { get; set; }
        public string EMP_END_TIME { get; set; }
        public string SUM_HOURS { get; set; }
    
        public virtual EMPLOYEES_COFFEE EMPLOYEES_COFFEE { get; set; }
    }
}
