//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EMPLOYEES_COFFEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES_COFFEE()
        {
            this.INVOICEs = new HashSet<INVOICE>();
            this.EQUIPMENTS = new HashSet<EQUIPMENT>();
        }

        
        public string EMP_ID { get; set; }
        public string EMP_FIRSTNAME { get; set; }
        public string EMP_LASTNAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string EMP_USERNAME { get; set; }
        [DataType(DataType.Password)]
        public string EMP_PASSWORD { get; set; }
        public string DEPT_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual EMP_HISTORY EMP_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT> EQUIPMENTS { get; set; }
    }
}
