//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT()
        {
            this.EMPLOYEES_COFFEE = new HashSet<EMPLOYEES_COFFEE>();
        }
    
        public string EQUIP_ID { get; set; }
        public string EQUIP_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<System.DateTime> INSURANCE_DATE { get; set; }
        public string BRANCH_ID { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEES_COFFEE> EMPLOYEES_COFFEE { get; set; }
    }
}
