//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public string INVOICE_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<decimal> INVOICE_PRICE { get; set; }
        public Nullable<decimal> INVOICE_POINT { get; set; }
        public string PROMO_ID { get; set; }
        public string EMP_ID { get; set; }
        public string BRANCH_ID { get; set; }
        public string USER_ID { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual EMPLOYEES_COFFEE EMPLOYEES_COFFEE { get; set; }
        public virtual PROMOTION PROMOTION { get; set; }
        public virtual USER USER { get; set; }
    }
}
