//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESOURCE()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.BRANCHes = new HashSet<BRANCH>();
        }
    
        public string RESOURCE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRANCH> BRANCHes { get; set; }
    }
}
