//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.INVOICEs = new HashSet<INVOICE>();
        }
        [Key]
        public string USER_ID { get; set; }
        [Required(ErrorMessage ="First Name is required")]
        public string FIRST_NAME { get; set; }
        [Required(ErrorMessage = "Last Name is required")]
        public string LAST_NAME { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        public string USER_SEX { get; set; }
        [Required(ErrorMessage = "PhoneNumber is required")]
        public string USER_TEL { get; set; }
        [Required(ErrorMessage = "E-mail is required")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter valid email.")]
        public string USER_EMAIL { get; set; }
        public Nullable<System.DateTime> USER_BD { get; set; }
        public Nullable<decimal> USER_POINT { get; set; }
        [Required(ErrorMessage = "Username is required")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
    }
}
